name: Deploy Ephemeral Instance

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "endofyearshow2021-${{ github.base_ref }}-${{ github.job }}"
          heroku_email: "erin@everyplace.net"
